version: '3'

volumes:
  postgres:

networks:
  postpossible:

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postpossible
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432